export const BOARD_EMPTY = "Board can't be empty"
export const COLUMN_EMPTY = "Column can't be empty"
export const BOARD_MAX_LENGTH_MESSAGE = "Board max length is 20"
export const COLUMN_MAX_LENGTH_MESSAGE = "Column max length is 20"
export const TASK_EMPTY = "Task can't be empty"
export const TASK_DESCRIPTION_EMPTY = "Task description can't be empty"
export const TASK_STATUS_EMPTY = "Task status can't be empty"
export const SUBTASK_EMPTY = "Subtask can't be empty"